In [1]:
import pandas as pd

filename = "../resource/holding.csv"

df = pd.read_csv(filename)

In [2]:
df

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10
...,...,...,...,...,...,...,...,...,...
32878713,3157350,2021/11/30,428,2021/12/21,0.11,25000.0,2.229475e+04,Bausch Health Companies Inc 5% 30-JAN-2028,071734AH
32878714,3157350,2021/11/30,429,2021/12/21,0.11,25000.0,2.148050e+04,Bausch Health Companies Inc 5.25% 30-JAN-2030,071734AJ
32878715,3157350,2021/11/30,429,2021/12/21,0.11,25000.0,2.148400e+04,Bausch Health Companies Inc 5% 15-FEB-2029,071734AM
32878716,3157350,2021/11/30,431,2021/12/21,0.10,25000.0,1.918738e+04,Endo DAC 6% 30-JUN-2028,29273DAC
32878717,3157350,2021/11/30,432,2021/12/21,0.08,25000.0,1.497188e+04,PBF Holding Company LLC 6% 15-FEB-2028,69318FAJ

## head()

In [3]:
# Get the first 5 rows

df.head()

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10

In [4]:
# Get the first n rows

n = 10
df.head(n)

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10
5,2998623,2020/11/30,6,2021/01/08,1.64,866386.0,1.997713e+08,GOLDMAN SACHS GROUP INC,38141G10
6,2998623,2020/11/30,7,2021/01/08,1.63,2194727.0,1.976352e+08,C S X CORP,12640810
7,2998623,2020/11/30,8,2021/01/08,1.60,5045923.0,1.939653e+08,AMERICAN INTERNATIONAL GROUP INC,02687478
8,2998623,2020/11/30,9,2021/01/08,1.59,1403360.0,1.937619e+08,P N C FINANCIAL SERVICES GRP INC,69347510
9,2998623,2020/11/30,10,2021/01/08,1.54,3065766.0,1.874409e+08,C B R E GROUP INC,12504L10

## tail()

In [5]:
# Get last 5 rows

df.tail()

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
32878713,3157350,2021/11/30,428,2021/12/21,0.11,25000.0,22294.75,Bausch Health Companies Inc 5% 30-JAN-2028,071734AH
32878714,3157350,2021/11/30,429,2021/12/21,0.11,25000.0,21480.50,Bausch Health Companies Inc 5.25% 30-JAN-2030,071734AJ
32878715,3157350,2021/11/30,429,2021/12/21,0.11,25000.0,21484.00,Bausch Health Companies Inc 5% 15-FEB-2029,071734AM
32878716,3157350,2021/11/30,431,2021/12/21,0.10,25000.0,19187.38,Endo DAC 6% 30-JUN-2028,29273DAC
32878717,3157350,2021/11/30,432,2021/12/21,0.08,25000.0,14971.88,PBF Holding Company LLC 6% 15-FEB-2028,69318FAJ

In [6]:
# Get last n rows

n = 10
df.tail(n)

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
32878708,3157350,2021/11/30,423,2021/12/21,0.12,25000.0,22810.50,Staples Inc 10.75% 15-APR-2027,855030AP
32878709,3157350,2021/11/30,424,2021/12/21,0.12,25000.0,22726.50,Sinclair Television Group Inc 4.125% 01-DEC-2030,829259BA
32878710,3157350,2021/11/30,425,2021/12/21,0.12,25000.0,22700.00,Bausch Health Companies Inc 6.25% 15-FEB-2029,071734AK
32878711,3157350,2021/11/30,426,2021/12/21,0.11,25000.0,22685.13,Sinclair Television Group Inc 5.5% 01-MAR-2030,829259AY
32878712,3157350,2021/11/30,427,2021/12/21,0.11,25000.0,22561.75,Service Properties Trust 4.375% 15-FEB-2030,44106MAY
32878713,3157350,2021/11/30,428,2021/12/21,0.11,25000.0,22294.75,Bausch Health Companies Inc 5% 30-JAN-2028,071734AH
32878714,3157350,2021/11/30,429,2021/12/21,0.11,25000.0,21480.50,Bausch Health Companies Inc 5.25% 30-JAN-2030,071734AJ
32878715,3157350,2021/11/30,429,2021/12/21,0.11,25000.0,21484.00,Bausch Health Companies Inc 5% 15-FEB-2029,071734AM
32878716,3157350,2021/11/30,431,2021/12/21,0.10,25000.0,19187.38,Endo DAC 6% 30-JUN-2028,29273DAC
32878717,3157350,2021/11/30,432,2021/12/21,0.08,25000.0,14971.88,PBF Holding Company LLC 6% 15-FEB-2028,69318FAJ

In [7]:
# Get certain rows

df[444:449]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
444,2998809,2020/11/30,17,2021/01/08,1.96,1542737.0,39154665.06,EQUITABLE HOLDINGS INC,29452E10
445,2998809,2020/11/30,18,2021/01/08,1.88,1883515.0,37632629.70,CARNIVAL CORP,14365830
446,2998809,2020/11/30,19,2021/01/08,1.80,260036.0,35903170.52,P N C FINANCIAL SERVICES GRP INC,69347510
447,2998809,2020/11/30,20,2021/01/08,1.74,150444.0,34778139.48,CUMMINS INC,23102110
448,2998809,2020/11/30,21,2021/01/08,1.71,725931.0,34278461.82,LINCOLN NATIONAL CORP,53418710

## loc[:, :]

In [8]:
# Get certain rows and columns by name

df.loc[[1,3,5,7], :]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
5,2998623,2020/11/30,6,2021/01/08,1.64,866386.0,1.997713e+08,GOLDMAN SACHS GROUP INC,38141G10
7,2998623,2020/11/30,8,2021/01/08,1.60,5045923.0,1.939653e+08,AMERICAN INTERNATIONAL GROUP INC,02687478

In [9]:
# Get certain rows and columns

df.loc[[1, 3, 5, 7], "portno":"market_val"]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08
5,2998623,2020/11/30,6,2021/01/08,1.64,866386.0,1.997713e+08
7,2998623,2020/11/30,8,2021/01/08,1.60,5045923.0,1.939653e+08

## iloc[:, :]

In [10]:
# Get certain rows and columns by index

df.iloc[[1,3,5,7], :]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
5,2998623,2020/11/30,6,2021/01/08,1.64,866386.0,1.997713e+08,GOLDMAN SACHS GROUP INC,38141G10
7,2998623,2020/11/30,8,2021/01/08,1.60,5045923.0,1.939653e+08,AMERICAN INTERNATIONAL GROUP INC,02687478

In [11]:
df.iloc[[1, 3, 5, 7], "portno":"market_val"]

TypeError: cannot do positional indexing on Index with these indexers [portno] of type str

In [12]:
df.iloc[[1, 3, 5, 7], 0:7]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08
5,2998623,2020/11/30,6,2021/01/08,1.64,866386.0,1.997713e+08
7,2998623,2020/11/30,8,2021/01/08,1.60,5045923.0,1.939653e+08

## columns and index

In [13]:
# Get columns

df.columns

Index(['portno', 'report_dt', 'security_rank', 'eff_dt', 'percent_tna',
       'nbr_shares', 'market_val', 'security_name', 'cusip'],
      dtype='object')

In [14]:
df.index

RangeIndex(start=0, stop=32878718, step=1)

# dtypes

In [15]:
df.dtypes

portno            object
report_dt         object
security_rank      int64
eff_dt            object
percent_tna      float64
nbr_shares       float64
market_val       float64
security_name     object
cusip             object
dtype: object

In [16]:
df["portno"].dtype

dtype('O')

In [17]:
df["security_rank"].dtype

dtype('int64')

In [18]:
df["market_val"].dtype

dtype('float64')

# unique()

In [19]:
df["portno"].unique()

array(['2998623', '2998638', '2998809', ..., '3157332', '315733e',
       '3157350'], dtype=object)

In [20]:
type(df["portno"].unique())

numpy.ndarray

# mean()

In [21]:
df["nbr_shares"].mean()

41548315.25043799

In [22]:
df["security_rank"].mean()

1077.9147216749752

In [23]:
df["percent_tna"].mean()

0.2945002086151897

In [24]:
df["market_val"].mean()

8366759.8750717705

In [25]:
df["cusip"].mean()

TypeError: can only concatenate str (not "int") to str

In [26]:
df[["nbr_shares", "security_rank", "percent_tna", "market_val"]].mean()

nbr_shares       4.154832e+07
security_rank    1.077915e+03
percent_tna      2.945002e-01
market_val       8.366760e+06
dtype: float64

In [27]:
df[["nbr_shares", "security_rank", "percent_tna", "market_val", "cusip"]].mean()

/var/folders/bv/8bbkzq895db366kq27vw262r0000gn/T/ipykernel_47226/3204749079.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df[["nbr_shares", "security_rank", "percent_tna", "market_val", "cusip"]].mean()

nbr_shares       4.154832e+07
security_rank    1.077915e+03
percent_tna      2.945002e-01
market_val       8.366760e+06
dtype: float64

## value_counts

In [28]:
df["portno"].value_counts()

3066654    223027
3086928    185325
306841b    181445
3100110    127403
306920d    120721
            ...
3092553         1
3069210         1
3065319         1
3077046         1
3078942         1
Name: portno, Length: 11920, dtype: int64

In [29]:
df2 = pd.DataFrame(
    {
        'num_legs': [2, 4, 4, 6],
        'num_wings': [2, 0, 0, 0]
    },
    index=['falcon', 'dog', 'cat', 'ant']
)
df2

        num_legs  num_wings
falcon         2          2
dog            4          0
cat            4          0
ant            6          0

In [30]:
df2.value_counts()

num_legs  num_wings
4         0            2
2         2            1
6         0            1
dtype: int64

In [31]:
type(df2.value_counts())

pandas.core.series.Series

In [32]:
df2.value_counts().index

MultiIndex([(4, 0),
            (2, 2),
            (6, 0)],
           names=['num_legs', 'num_wings'])

In [33]:
df.value_counts()

portno   report_dt   security_rank  eff_dt      percent_tna  nbr_shares  market_val    security_name                                                   cusip
2998623  2020/11/30  1              2021/01/08  2.55         7078982.0   3.103426e+08  GENERAL MOTORS CO                                               37045V10    1
309473d  2021/04/30  1397           2021/06/07  0.00         872000.0    5.560842e+04  South Africa, Republic of (Government) 8% 31-JAN-2030           S69124VP    1
                     1428           2021/06/07  0.00         26639.0     2.902364e+04  Freddie Mac 01-JUL-2042 Q09739                                  3132GVEL    1
                     1427           2021/06/07  0.00         30000.0     3.011460e+04  Escambia County Health Facilities Authority 3.607% 15-AUG-2040  296110GG    1
                     1424           2021/06/07  0.00         31000.0     3.122589e+04  Martin Marietta Materials Inc 2.5% 15-MAR-2030                  573284AV    1
                                                                                                                                                                  ..
3074208  2021/10/31  4              2021/12/07  1.36         16305000.0  1.974063e+07  Anheuser-Busch Companies LLC 4.7% 01-FEB-2036                   03522AAH    1
                     3              2021/12/07  1.42         20920000.0  2.057662e+07  Goldman Sachs Group Inc 10-SEP-2027                             38141GYG    1
                     2              2021/12/07  1.66         24724000.0  2.403888e+07  Morgan Stanley 16-SEP-2036                                      61747YEF    1
                     1              2021/12/07  1.70         25280000.0  2.460111e+07  Bank of America Corp 21-SEP-2036                                06051GKC    1
3157350  2021/11/30  432            2021/12/21  0.08         25000.0     1.497188e+04  PBF Holding Company LLC 6% 15-FEB-2028                          69318FAJ    1
Length: 31802790, dtype: int64

In [34]:
df.value_counts().index

MultiIndex([('2998623', '2020/11/30',    1, '2021/01/08', 2.55, ...),
            ('309473d', '2021/04/30', 1397, '2021/06/07',  0.0, ...),
            ('309473d', '2021/04/30', 1428, '2021/06/07',  0.0, ...),
            ('309473d', '2021/04/30', 1427, '2021/06/07',  0.0, ...),
            ('309473d', '2021/04/30', 1424, '2021/06/07',  0.0, ...),
            ('309473d', '2021/04/30', 1424, '2021/06/07',  0.0, ...),
            ('309473d', '2021/04/30', 1422, '2021/06/07',  0.0, ...),
            ('309473d', '2021/04/30', 1422, '2021/06/07',  0.0, ...),
            ('309473d', '2021/04/30', 1418, '2021/06/21',  0.0, ...),
            ('309473d', '2021/04/30', 1418, '2021/06/07',  0.0, ...),
            ...
            ('3074208', '2021/10/31',    9, '2021/12/07', 0.94, ...),
            ('3074208', '2021/10/31',    8, '2021/12/07', 0.98, ...),
            ('3074208', '2021/10/31',    7, '2021/12/07', 0.99, ...),
            ('3074208', '2021/10/31',    6, '2021/12/07', 1.01, ...),
            ('3074208', '2021/10/31',    5, '2021/12/07', 1.06, ...),
            ('3074208', '2021/10/31',    4, '2021/12/07', 1.36, ...),
            ('3074208', '2021/10/31',    3, '2021/12/07', 1.42, ...),
            ('3074208', '2021/10/31',    2, '2021/12/07', 1.66, ...),
            ('3074208', '2021/10/31',    1, '2021/12/07',  1.7, ...),
            ('3157350', '2021/11/30',  432, '2021/12/21', 0.08, ...)],
           names=['portno', 'report_dt', 'security_rank', 'eff_dt', 'percent_tna', 'nbr_shares', 'market_val', 'security_name', 'cusip'], length=31802790)

## describe()

In [35]:
df.describe()

       security_rank   percent_tna    nbr_shares    market_val
count   3.287872e+07  3.287872e+07  3.287872e+07  3.287872e+07
mean    1.077915e+03  2.945002e-01  4.154832e+07  8.366760e+06
std     1.793852e+03  1.651244e+00  8.185030e+09  1.376690e+08
min     1.000000e+00 -2.628000e+02 -1.188360e+13 -3.157247e+10
25%     1.310000e+02  1.000000e-02  8.000000e+03  9.254227e+04
50%     4.230000e+02  4.000000e-02  1.000000e+05  5.251210e+05
75%     1.228000e+03  1.900000e-01  8.250000e+05  2.523780e+06
max     1.866500e+04  3.822500e+02  9.665837e+12  7.359335e+10

## Filter data

In [36]:
filter_portno_2998623 = df["portno"] == "2998623"
filter_portno_2998623

0            True
1            True
2            True
3            True
4            True
            ...
32878713    False
32878714    False
32878715    False
32878716    False
32878717    False
Name: portno, Length: 32878718, dtype: bool

In [37]:
df[filter_portno_2998623]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10
...,...,...,...,...,...,...,...,...,...
30001404,2998623,2021/10/31,339,2021/12/07,0.00,5.0,5.650000e+00,Freddie Mac 01-FEB-2037 A57210,3128KLAK
30001405,2998623,2021/10/31,339,2021/12/07,0.00,678.0,8.030000e+02,Ginnie Mae 2 20-DEC-2030 003011,36202DKY
30001406,2998623,2021/10/31,339,2021/12/07,0.00,1021.0,1.223010e+03,Ginnie Mae 2 20-JAN-2031 003028,36202DLH
30001407,2998623,2021/10/31,339,2021/12/07,0.00,3164.0,3.177910e+03,Gvt Ntl Mrtg Asn 15-JUN-2026 422949,36206VZN
30001408,2998623,2021/10/31,339,2021/12/07,0.00,5140.0,5.159240e+03,Fannie Mae 01-JUL-2032 642656,31390C5R

In [38]:
filter_reportdt_20210131 = df["report_dt"] == "2021/01/31"

In [39]:
df[filter_portno_2998623 & filter_reportdt_20210131]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
4933836,2998623,2021/01/31,1,2021/03/08,2.72,6473164.0,3.280600e+08,GENERAL MOTORS CO,37045V10
4933837,2998623,2021/01/31,4,2021/03/08,1.89,7604367.0,2.272185e+08,WELLS FARGO & CO NEW,94974610
4933838,2998623,2021/01/31,5,2021/03/08,1.85,2860448.0,2.229719e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
4933839,2998623,2021/01/31,6,2021/03/08,1.72,2608008.0,2.077278e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4933840,2998623,2021/01/31,7,2021/03/08,1.57,4761997.0,1.898132e+08,CORTEVA INC,22052L10
...,...,...,...,...,...,...,...,...,...
5980019,2998623,2021/01/31,347,2021/03/23,0.00,780.0,9.503700e+02,Ginnie Mae 2 20-DEC-2030 003011,36202DKY
5980020,2998623,2021/01/31,347,2021/03/23,0.00,1280.0,1.577000e+03,Ginnie Mae 2 20-JAN-2031 003028,36202DLH
5980021,2998623,2021/01/31,347,2021/03/23,0.00,3608.0,3.624500e+03,Gvt Ntl Mrtg Asn 15-JUN-2026 422949,36206VZN
5980022,2998623,2021/01/31,347,2021/03/23,0.00,5562.0,5.583650e+03,Fannie Mae 01-JUL-2032 642656,31390C5R
5980023,2998623,2021/01/31,347,2021/03/23,0.00,0.0,2.400000e-01,Fannie Mae 01-MAR-2021 866003 Pd Down,31409BDG